apiVersion: v1
kind: Service
metadata:
  namespace: actualbudget
  labels:
    io.kompose.service: actualbudgetui
  name: actualbudgetui
spec:
  ports:
    - name: "actualbudgetui"
      port: 80
      targetPort: 5006
  selector:
    io.kompose.service: actualbudgetui

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actualbudget-ingress
  namespace: actualbudget
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: {{ .Values.baseurl}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: actualbudgetui
            port: 
              name: "actualbudgetui"
  tls:
  - secretName: actualbudgetcert-wild-4-tls
    hosts:
      - {{ .Values.baseurl}}
