apiVersion: apps/v1
kind: Deployment
metadata:
  name: actualbudgetui
  namespace: actualbudget
  labels:
    io.kompose.service: actualbudgetui
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: actualbudgetui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: actualbudgetui
    spec:
      containers:
        - image: "{{$.Values.image.repository }}:{{$.Values.image.tag | toString }}"
          name: actualbudgetui
          imagePullPolicy: Always
          ports:
            - containerPort: 5006
          resources:
            requests:
              memory: "8Mi"
              cpu: "30m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
status: {}
