apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcaslicer
  namespace: {{$.Values.namespace}}
  labels:
    io.kompose.service: orcaslicer
spec:
  revisionHistoryLimit: 1
  replicas: {{$.Values.replicas}}
  selector:
    matchLabels:
      io.kompose.service: orcaslicer
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: orcaslicer
    spec:
      containers:
        - 
          env: []
          image: "{{$.Values.image.repository }}:{{$.Values.image.tag | toString }}"
          name: orcaslicer
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      restartPolicy: Always
status: {}
