apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: amq
  namespace: wordsolver
  labels:
    io.kompose.service: amq
spec:
  deploymentPlan:
    size: 1
    image: placeholder
  acceptors:
  - name: "stomp"
    port: 61613
    protocols: stomp

---

apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: wordsolverin
spec:
  addressName: wordsolver.input
  queueName: wordsolver.input
  routingType: multicast
  removeFromBrokerOnDelete: true
---

apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: wordsolverout
spec:
  addressName: wordsolver.output
  queueName: wordsolver.output
  routingType: multicast
  removeFromBrokerOnDelete: true

---

apiVersion: v1
kind: Service
metadata:
  namespace: wordsolver
  creationTimestamp: null
  labels:
    io.kompose.service: amq
  name: amq
spec:
  ports:
    - name: "61613"
      port: 61613
      targetPort: 61613
    - name: "8161"
      port: 8162
      targetPort: 8161
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: amq
