apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: wordsolverin
spec:
  addressName: wordsolver.input
  queueName: wordsolver.input
  routingType: multicast
  removeFromBrokerOnDelete: true
---

apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: wordsolverout
spec:
  addressName: wordsolver.output
  queueName: wordsolver.output
  routingType: multicast
  removeFromBrokerOnDelete: true
---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: wordsolver.heartbeat
spec:
  addressName: wordsolver.heartbeat
  queueName: wordsolver.heartbeat
  routingType: multicast
  removeFromBrokerOnDelete: true
