---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: wordsolver
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
    version: {{ $.Chart.Version }}
  {{- $str := "producer" | lower}}
  {{- $str = print $str $.Values.completions}}
  {{- $str = print $str $.Values.parallelism}}
  {{- $str = print $str "-" $.Values.producerImage.tag }}
  {{- $str = print $str $.Values.inputs }}
  {{- $str = print $str | adler32sum  }}
  name: {{ $str | quote}}
  namespace: wordsolver
spec:
  backoffLimit: 2
  template:
    spec:
    spec:
      containers:
      - image: "{{$.Values.producerImage.repository }}:{{$.Values.producerImage.tag | toString }}"
        imagePullPolicy: {{ $.Values.pullPolicy }}
        name: "producer"
        resources: 
          limits:
            cpu: 500m 
            memory: 25Mi
          requests:
            cpu: 10m
            memory: 25Mi
        env:
          - name: "INPUTS"
            value: {{$.Values.inputs | quote}}
          - name: "USERNAME"
            valueFrom:
              secretKeyRef:
                name: amq-credentials-secret
                key: AMQ_USER
      restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordsolver-resultprinter
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
    version: {{ $.Chart.Version }}
  name: wordsolverresultprinter
  namespace: wordsolver
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: wordsolver-resultprinter
  template:
    metadata:
      labels:
        app: wordsolver-resultprinter
    spec:
      containers:
      - image: "{{$.Values.resultprinterImage.repository }}:{{$.Values.resultprinterImage.tag | toString }}"
        imagePullPolicy: {{ $.Values.pullPolicy }}
        name: "resultprinter"
        resources: 
          limits:
            cpu: 30m 
            memory: 25Mi
          requests:
            cpu: 10m
            memory: 25Mi
        env:
          - name: "INPUTS"
            value: {{$.Values.inputs | quote}}
          - name: "REPORT_FREQ"
            value: {{$.Values.reportFreq | quote}}
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordsolver-processor
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
    version: {{ $.Chart.Version }}
  name: wordsolverprocessor
  namespace: wordsolver
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: wordsolver-processor
  template:
    metadata:
      labels:
        app: wordsolver-processor
    spec:
      containers:
      - image: "{{$.Values.processorImage.repository }}:{{$.Values.processorImage.tag | toString }}"
        imagePullPolicy: {{ $.Values.pullPolicy }}
        name: "processor"
        resources: 
          limits:
            cpu: 50m 
            memory: 50Mi
          requests:
            cpu: 30m
            memory: 25Mi
        env:
          - name: "REPORT_FREQ"
            value: {{$.Values.reportFreq | quote}}
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: wordsolverprocessor
 namespace: wordsolver
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: wordsolverprocessor
 minReplicas: 1
 maxReplicas: {{$.Values.processorScale}}
 targetCPUUtilizationPercentage: 70
 
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: wordsolverresultprinter
 namespace: wordsolver
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: wordsolverresultprinter
 minReplicas: 1
 maxReplicas: 1
 targetCPUUtilizationPercentage: 50
