
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordsolver-processor
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
    version: {{ $.Chart.Version }}
  name: wordsolverprocessor
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: wordsolver-processor
  template:
    metadata:
      labels:
        app: wordsolver-processor
    spec:
      containers:
      - image: "{{$.Values.processorImage.repository }}:{{$.Values.processorImage.tag | toString }}"
        imagePullPolicy: {{ $.Values.pullPolicy }}
        name: "processor"
        resources: 
          limits:
            cpu: 50m 
            memory: 50Mi
          requests:
            cpu: 30m
            memory: 25Mi
        env:
          - name: "USERNAME"
            valueFrom:
              secretKeyRef:
                name: amqpassword
                key: username
          - name: "PASSWORD"
            valueFrom:
              secretKeyRef:
                name: amqpassword
                key: password
          - name: "PROCESSING_LIMIT"
            value: {{$.Values.processinglimit | quoted }}
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: wordsolverprocessor
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: wordsolverprocessor
 minReplicas: 1
 maxReplicas: {{$.Values.processorScale}}
 targetCPUUtilizationPercentage: 70

