apiVersion: v1
kind: Service
metadata:
  namespace: workdaycounter
  labels:
    io.kompose.service: workdaycounter
  name: workdaycounter
spec:
  ports:
    - name: "workdaycounter"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: workdaycounter

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workdaycounter-ingress
  namespace: workdaycounter
  annotations:
    acme.cert-manager.io/http01-ingress-class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: {{ .Values.baseurl}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: workdaycounter
            port: 
              name: "workdaycounter"
  tls:
  - secretName: workdaycountercert-wild-tls
    hosts:
      - {{ .Values.baseurl}}
