apiVersion: v1
kind: Service
metadata:
  namespace: optimalpowercaldulator
  labels:
    io.kompose.service: optimalpowercaldulator
  name: optimalpowercaldulator
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: optimalpowercaldulator

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: optimalpowercaldulator-ingress
  namespace: optimalpowercaldulator
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: {{ .Values.baseurl}}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: optimalpowercaldulator
            port: 
              name: "http"
  tls:
  - secretName: optimalpowercaldulatorcert-wild-tls
    hosts:
      - {{ .Values.baseurl}}
