apiVersion: apps/v1
kind: Deployment
metadata:
  name: workdaycounter
  namespace: workdaycounter
  labels:
    io.kompose.service: workdaycounter
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: workdaycounter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: workdaycounter
    spec:
      containers:
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 99999
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image: "{{$.Values.image.repository }}:{{$.Values.image.tag | toString }}"
          name: workdaycounter
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "8Mi"
              cpu: "30m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
      restartPolicy: Always
status: {}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: workdaycounterscaler
  namespace: workdaycounter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workdaycounter
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
