kubernetes:
  host: https://kubernetes.default
namespace: default
pullPolicy: IfNotPresent
title: WordSolver
inputs:
  - "abcdef"
  - "ghijkl"
  - "mnopqr"
  - "stuvwx"
  - "yzæøå"
reportFreq: 100000
completions: 1
parallelism: 1
producerImage:
  repository: rasmus256docker/wordsolver-producer
  tag: 25
  
processorImage:
  repository: rasmus256docker/wordsolver-processor
  tag: 25
  
resultprinterImage:
  repository: rasmus256docker/wordsolver-resultprinter
  tag: 25
