kubernetes:
  host: https://kubernetes.default
namespace: default
pullPolicy: IfNotPresent
title: WordSolver
first: "send"
second: "more"
third: "money"
completions: 1
parallelism: 1
image:
  repository: rasmus256docker/wordsolver
  tag: 3