kubernetes:
  host: https://kubernetes.default
namespace: default
pullPolicy: IfNotPresent
title: WordSolver
ingressEnabled: "true"
inputs: "abcdef ghijkl mnopqrt"
lockedinit: 'm,1;o,0;s,9'
processinglimit: 3
completions: 1
parallelism: 1
processorScale: 9
producerImage:
  repository: rasmus256docker/wordsolver-producer
  tag: 136
processorImage:
  repository: rasmus256docker/wordsolver-processor
  tag: 136
resultprinterImage:
  repository: rasmus256docker/wordsolver-resultprinter
  tag: 138
