kubernetes:
  host: https://kubernetes.default
namespace: default
pullPolicy: IfNotPresent
title: WordSolver
inputs:
  - "send"
  - "many"
  - "much"
  - "more"
  - "money"
reportFreq: 100000
completions: 1
parallelism: 1
image:
  repository: rasmus256docker/wordsolver
  tag: 16
  
