apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\rasmu\cluster\kompose-windows-amd64.exe convert
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: hass
  name: hass
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      io.kompose.service: hass
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\rasmu\cluster\kompose-windows-amd64.exe convert
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: hass
    spec:
      nodeSelector:
        pi: "false"
      containers:
        - env:
            - name: TZ 
              value: Europe/Copenhagen
          image: homeassistant/home-assistant:2022.11.4
          name: hass
          ports:
            - containerPort: 8123
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: /config/configuration.yaml
              readOnly: true
              subPath: configuration.yaml
              name: configurationconfigmap
            - name: hass-storagev
              mountPath: /config
#        - image: postgres:14
#          name: pgsql
#          ports:
#          - containerPort: 5432
#          env:
#            - name: POSTGRES_PASSWORD
#              value: mypassword
#            - name: PGDATA
#              value: /var/lib/postgresql/data/pgdata
#          volumeMounts:
#            - mountPath: /var/lib/postgresql/data
#              name: postgres-pv-storage
      restartPolicy: Always
      volumes:
        - name: hass-storagev
          persistentVolumeClaim:
            claimName: hass-storage
        - name: configurationconfigmap
          configMap:
            name: hassconfigmap
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
status: {}
