apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: openfaas-ingress
  namespace: openfaas

spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`openfaas.hosrasmus.hopto.org`)
      kind: Rule
      services:
        - name: gateway
          port: 8080
          weight: 1
  tls:
    secretName: openfaascert-2-2tls
    options:
      name: opt
      namespace: openfaas
    certResolver: letsencrypt-prod
    domains:
    - main: openfaas.hosrasmus.hopto.org
