---
apiVersion: v1
kind: List
items:
{{- range .Values.images }}
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      app: helloworld
      chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
      release: {{ $.Release.Name | quote }}
      heritage: {{ $.Release.Service | quote }}
      version: {{ $.Chart.Version }}
    name: range-testday1p1-1
  spec:
    template:
      spec:
      spec:
        containers:
        {{- range .parts }}
        - image: "{{.repository }}:{{.tag }}"
          imagePullPolicy: {{ $.Values.pullPolicy }}
          name: helloworld-{{.tag | replace "." "-"}}
        {{- end }}
        restartPolicy: Never

{{- end }}    
