---
apiVersion: v1
kind: List
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: {{ .Chart.Version }}
    name: helloworld
  spec:
    template:
      spec:
      spec:
        containers:
        - image: "{{ .Values.helloworld.image.name }}:{{ .Values.helloworld.image.tag }}"
          imagePullPolicy: {{ .Values.helloworld.image.pullPolicy }}
          name: helloworld
        restartPolicy: Never
