---
apiVersion: v1
kind: List
items:
{{- range .Values.images }}
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      app: helloworld
      chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
      release: {{ $.Release.Name | quote }}
      heritage: {{ $.Release.Service | quote }}
      version: {{ $.Chart.Version }}
    {{- $postfix := "" }}
    {{- range $i, $e := .parts }}
    {{- $postfix = print $postfix "-" $e.image.tag }}
    {{- end }}
    {{- $postfix := $postfix | adler32sum }}
    {{- $str := .title}}
    name: {{ $str "-" $postfix }}
  spec:
    completions: 1
    backoffLimit: 2
    template:
      spec:
      spec:
        containers:
        {{- range $i, $e := .parts }}
        - image: "{{$e.image.repository }}:{{$e.image.tag | toString }}"
          imagePullPolicy: {{ $.Values.pullPolicy }}
          name: {{ $e.image.repository | toString | replace "/" "-" | replace "_" "-"}}-{{ $e.image.tag | toString | replace "." "-" }}
        {{- end }}
        restartPolicy: Never

{{- end }}    
