---
apiVersion: v1
kind: List
items:
{{- range .Values.images }}
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      app: helloworld
      chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
      release: {{ $.Release.Name | quote }}
      heritage: {{ $.Release.Service | quote }}
      version: {{ $.Chart.Version }}
    {{- $str := .title }}
    {{- range $i, $e := .parts }}
    {{- if $i }}
    {{- $str = print $str "-" }}
    {{- end }}
    {{- $str = print $str $e.image.tag }}
    {{- end }}
    name: {{ $str }}
  spec:
    completions: 5
    parallelism: 1
    template:
      spec:
      spec:
        containers:
        {{- range $i, $e := .parts }}
        - image: "{{$e.image.repository }}:{{$e.image.tag | toString }}"
          imagePullPolicy: {{ $.Values.pullPolicy }}
          name: {{ $e.image.repository | toString | replace "/" "-" | replace "_" "-"}}-{{ $e.image.tag | toString | replace "." "-" }}
        {{- end }}
        restartPolicy: Never

{{- end }}    
