---
apiVersion: v1
kind: List
items:
{{- range .Values.images }}
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      app: helloworld
      chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
      release: {{ $.Release.Name | quote }}
      heritage: {{ $.Release.Service | quote }}
      version: {{ $.Chart.Version }}
    {{- $str := "" }}
    {{- range $i, $e := .parts }}
    {{- if $i }}
    {{- $str = print $str "," }}
    {{- end }}
    {{- $str = print $str $e.tag }}
    {{- end }}
    name: {{ $str }}
  spec:
    template:
      spec:
      spec:
        containers:
        {{- range .parts }}
        - image: "{{.image.repository }}:{{.image.tag }}"
          imagePullPolicy: {{ $.Values.pullPolicy }}
          name: helloworld-{{ .image.tag | toString | replace "." "-" }}
        {{- end }}
        restartPolicy: Never

{{- end }}    
