apiVersion: v1
kind: Service
metadata:
  namespace: firekabale
  labels:
    io.kompose.service: firekabaleui
  name: firekabaleui
spec:
  ports:
    - name: "firekabaleui"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: firekabaleui

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firekabale-ingress
  namespace: firekabale
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: {{ .Values.baseurl}}
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: firekabaleui
            port: 
              name: "firekabaleui"
  tls:
  - secretName: firekabalecert-wild-4-tls
    hosts:
      - {{ .Values.baseurl}}
