apiVersion: apps/v1
kind: Deployment
metadata:
  name: firekabaleui
  namespace: firekabale
  labels:
    io.kompose.service: firekabaleui
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: firekabaleui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: firekabaleui
    spec:
      containers:
        - image: "{{$.Values.uiimage.repository }}:{{$.Values.uiimage.tag | toString }}"
          name: firekabaleui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "8Mi"
              cpu: "30m"
            limits:
              memory: "64Mi"
              cpu: "50m"
      restartPolicy: Always
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: firekabaleuitwo
  namespace: firekabale
  labels:
    io.kompose.service: firekabaleuitwo
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: firekabaleuitwo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: firekabaleuitwo
    spec:
      containers:
        - image: "{{$.Values.uicanaryimage.repository }}:{{$.Values.uicanaryimage.tag | toString }}"
          name: firekabaleuitwo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "8Mi"
              cpu: "30m"
            limits:
              memory: "64Mi"
              cpu: "50m"
      restartPolicy: Always
status: {}
