apiVersion: v1
kind: Service
metadata:
  namespace: spotifyrandom
  labels:
    io.kompose.service: spotifyrandomui
  name: spotifyrandomui
spec:
  ports:
    - name: "spotifyrandomui"
      port: 80
      targetPort: 8000
  selector:
    io.kompose.service: spotifyrandomui

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotifyrandom-ingress
  namespace: spotifyrandom
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: {{ .Values.baseurl}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spotifyrandomui
            port: 
              name: "spotifyrandomui"
  tls:
  - secretName: spotifyrandomcert-wild-4-tls
    hosts:
      - {{ .Values.baseurl}}
