apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotifyrandomui
  namespace: spotifyrandom
  labels:
    io.kompose.service: spotifyrandomui
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spotifyrandomui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: spotifyrandomui
    spec:
      containers:
        - image: "{{$.Values.image.repository }}:{{$.Values.image.tag | toString }}"
          name: spotifyrandomui
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "8Mi"
              cpu: "30m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
status: {}
