---
apiVersion: v1
kind: List
items:
{{- range .Values.images }}
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      app: helloworld
      chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
      release: {{ $.Release.Name | quote }}
      heritage: {{ $.Release.Service | quote }}
      version: {{ $.Chart.Version }}
    {{- $postfix := print $.Values.completions "-" $.Values.parallelism }}
    {{- range $i, $e := .parts }}
    {{- $postfix = print $postfix "-" $e.image.tag }}
    {{- end }}
    {{- $postfix := $postfix | adler32sum }}
    {{- $str := print .title "-" $postfix}}
    name: {{ $str  }}
  spec:
    completions: {{ $.Values.completions }}
    parallelism: {{ $.Values.parallelism }}
    backoffLimit: 2
    template:
      spec:
      spec:
        containers:
        {{- range $i, $e := .parts }}
        - image: "{{$e.image.repository }}:{{$e.image.tag | toString }}"
          imagePullPolicy: {{ $.Values.pullPolicy }}
          name: {{ $e.image.repository | toString | replace "/" "-" | replace "_" "-"}}-{{ $e.image.tag | toString | replace "." "-" }}
        {{- end }}
        restartPolicy: Never

{{- end }}    
---
apiVersion: v1
kind: List
items:
{{- range .Values.images }}
  {{- $title := .title }}
  {{- range $i, $e := .parts }}
  {{- $partName := add1 $i}
  {{ $addName := print $title "_part" $partName }}
- apiVersion: broker.amq.io/v1beta1
  kind: ActiveMQArtemisAddress
  metadata:
    name: {{$addName |replace "_" "-"}}
    namespace: adventofcode
  spec:
    addressName: {{$addName}}
    queueName: {{$addName}}
    routingType: multicast
    removeFromBrokerOnDelete: true
  {{- end }}    
{{- end }}    
---
