---
apiVersion: v1
kind: List
items:
{{- range $i, $repo := .Values.repositories }}
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      app: helloworld
      chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
      release: {{ $.Release.Name | quote }}
      heritage: {{ $.Release.Service | quote }}
      version: {{ $.Chart.Version }}
    {{- $postfix := print $.Values.completions "-" $.Values.parallelism }}
    {{- $postfix = print $postfix "-" .Values.image.tag }}
    {{- $postfix := $postfix | adler32sum }}
    {{- $str := print $repo "-" $postfix}}
    name: {{ $str  }}
    namespace: adventofcode
  spec:
    completions: {{ $.Values.completions }}
    parallelism: {{ $.Values.parallelism }}
    backoffLimit: 2
    template:
      spec:
      spec:
        containers:
        - image: "{{$repo }}:{{.Values.image.tag | toString }}"
          imagePullPolicy: {{ $.Values.pullPolicy }}
          name: {{ $repo | toString | replace "/" "-" | replace "_" "-"}}-{{ .Values.image.tag | toString | replace "." "-" }}
          env:
            - name: "USERNAME"
              valueFrom:
                secretKeyRef:
                  name: amqpassword
                  key: username
            - name: "PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: amqpassword
                  key: password
        {{- end }}
        restartPolicy: Never

{{- end }}    
---
apiVersion: v1
kind: List
items:
{{- range .Values.images }}
  {{- $title := .title }}
  {{- range $i, $e := .parts }}
  {{- $partName := add1 $i}}
  #adventofcode.day6.part1
  {{ $addName := print "adventofcode." $title ".part" $partName }}
- apiVersion: broker.amq.io/v1beta1
  kind: ActiveMQArtemisAddress
  metadata:
    name: {{$addName |replace "_" "-" |replace "." "-"}}
    namespace: adventofcode
  spec:
    addressName: {{$addName}}
    queueName: {{$addName}}
    routingType: multicast
    removeFromBrokerOnDelete: true
  {{- end }}    
{{- end }}    
---
