apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d1p1
spec:
  template:
    spec:
      containers:
      - name: day1-part1
        image: rasmus256docker/advent_of_code_day1_part1:1672772558
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d1reader
spec:
  template:
    spec:
      containers:
      - name: day1-part1
        image: rasmus256docker/advent_of_code_day1_event_reader:1672773406
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d1p1_event
spec:
  template:
    spec:
      containers:
      - name: day1-part1
        image: rasmus256docker/advent_of_code_day1_part1_event:1672773406
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d1p2
spec:
  template:
    spec:
      containers:
      - name: day1-part2
        image: rasmus256docker/advent_of_code_day1_part2:1672772558
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d2p1
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day2_part1:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d2p2
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day2_part2:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d3p1
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day3_part1:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d3p2
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day3_part2:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d4p1
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day4_part1:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d4p2
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day4_part2:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d5p1
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day5_part1:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d5p2
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day5_part2:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d6p1
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day6_part1:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d6p2
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day6_part2:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d7p1
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day7_part1:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d7p2
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day7_part2:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d8p1
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day8_part1:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d8p2
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day8_part2:1672772558
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d9p1
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day9_part1:1672772558
      restartPolicy: Never
  backoffLimit: 0

---
apiVersion: batch/v1
kind: Job
metadata:
  name: adventofcode-d9p2
spec:
  template:
    spec:
      containers:
      - name: solution
        image: rasmus256docker/advent_of_code_day9_part2:1672772558
      restartPolicy: Never
  backoffLimit: 0
