kubernetes:
  host: https://kubernetes.default
namespace: spotifyrandomalbum
pullPolicy: IfNotPresent
title: spotifyrandomalbum
replicas: 0
baseurl: spotify.hosrasmus.hopto.org
image:
  repository: docker.io/stefanmich/spotifyrandomalbum
  tag: "40@sha256:99f144c2f779f2d7147352e4f6de9f230b3139d1ff2a25f9bb428abae026125e"
spotipyconfig:
  clientid: "clientid"
  clientsecret: "clientsecret"
  redirecturi: "redirecturi"
djangoconfig:
  allowedhosts: "spotify.hosrasmus.hopto.org"
  trustedorigins: ""
