kubernetes:
  host: https://kubernetes.default
namespace: spotifyrandomalbum
pullPolicy: IfNotPresent
title: spotifyrandomalbum
replicas: 0
baseurl: spotify.hosrasmus.hopto.org
image:
  repository: docker.io/stefanmich/spotifyrandomalbum
  tag: "39@sha256:13c3cf6f9884260761b86858e6403adaee955e6555293cdd5b83a0402054fe74"
spotipyconfig:
  clientid: "clientid"
  clientsecret: "clientsecret"
  redirecturi: "redirecturi"
djangoconfig:
  allowedhosts: "spotify.hosrasmus.hopto.org"
  trustedorigins: ""
