apiVersion: apps/v1
kind: Deployment
metadata:
  name: cakeotron
  namespace: cake
  labels:
    io.kompose.service: cakeotron
spec:
  replicas: 2
  minReadySeconds: 2
  selector:
    matchLabels:
      io.kompose.service: cakeotron
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: cakeotron
    spec:
      containers:
        - env:
          - name: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
            value: "false"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 99999
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image: rasmus256docker/cakeotron:20220910123341
          name: cakeotron
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              memory: "8Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          volumeMounts:
            - mountPath: /
              name: tmpfs-1
          volumes:
            - name: tmpfs-1
              emptyDir: {}
      restartPolicy: Always
status: {}
