apiVersion: v1
kind: Service
metadata:
  namespace: cake
  labels:
    io.kompose.service: cakeotron
  name: cakeotron
spec:
  ports:
    - name: "cake"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: cakeotron

---
apiVersion: v1
kind: Service
metadata:
  namespace: cake
  labels:
    io.kompose.service: cakeotron-dateservice
  name: cakeotron-dateservice
spec:
  ports:
    - name: "cake"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: cakeotron-dateservice

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cake-ingress
  namespace: cake
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: {{ .Values.baseurl}}
    http:
      paths:
      - path: /dates
        pathType: Prefix
        backend:
          service:
            name: cakeotron-dateservice
            port: 
              name: "cake"
      - path: /
        pathType: Exact
        backend:
          service:
            name: cakeotron
            port: 
              name: "cake"
      - path: /criteria
        pathType: Exact
        backend:
          service:
            name: cakeotron
            port: 
              name: "cake"

  tls:
  - secretName: cakecert-wild-5-tls
    hosts:
      - {{ .Values.baseurl}}
