apiVersion: v1
kind: Service
metadata:
  namespace: cake
  annotations:
    kompose.cmd: C:\Users\rasmu\cluster\kompose-windows-amd64.exe convert
    acme.cert-manager.io/http01-ingress-class: traefik
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: cakeotron
  name: cakeotron
spec:
  type: LoadBalancer
  ports:
    - name: "cake"
      port: 4000
      targetPort: 80
  selector:
    io.kompose.service: cakeotron
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cake-ingress
  namespace: cake
  annotations:
    acme.cert-manager.io/http01-ingress-class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: {{ .Values.baseurl}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cakeotron
            port: 
              name: "cake"
  tls:
  - secretName: cakecert-wild-4-tls
    hosts:
      - {{ .Values.baseurl}}
