kubernetes:
  host: https://kubernetes.default
namespace: actualbudget
pullPolicy: IfNotPresent
title: actualbudget
canaryweight: 0
baseurl: budget.hosrasmus.hopto.org
image:
  repository: docker.io/actualbudget/actual-server
  tag: "25.2.1-alpine"