apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chickenkeeper-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: {{ .Values.baseurl }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: chickenkeeper-backend
            port:
              name: http
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chickenkeeper-ui
            port:
              name: http
  tls:
  - secretName: chickenkeeper-tls
    hosts:
      - {{ .Values.baseurl }}
