apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: chickenkeeper-backend
  name: chickenkeeper-backend
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/name: chickenkeeper-backend
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: chickenkeeper-ui
  name: chickenkeeper-ui
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: chickenkeeper-ui
