apiVersion: v1
kind: ConfigMap
metadata:
  name: hassconfigmap
data:
  configuration.yaml: |
  {{`
    #Configure a default setup of Home Assistant (frontend, api, etc)
    default_config:
    # recorder:
    #   db_url: "postgresql://homeassistant:yourpassword@localhost:5432/homeassistant_db"
    #   db_retry_wait: 3 # Wait 15 seconds before retrying
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 172.30.33.3
        - 127.0.0.1
        - ::1
        - 10.42.0.8
    # Text to speech
    tts:
      - platform: google_translate
    template:
    - sensor:
      - name: "Electricity Cost"
        unique_id: electricity_cost
        device_class: monetary
        unit_of_measurement: "kr/kWh"
        state: >
          {{ 1.25 * (float(states('sensor.eloverblik_tariff_sum')) + float(states('sensor.nordpool_kwh_dk1_dkk_3_10_0'))) }}
        attributes:
          today: >
            {% if state_attr('sensor.nordpool_kwh_dk1_dkk_3_10_0', 'today') %}
              {% set ns = namespace (prices=[]) %}
              {% for h in range(24) %}
                {% set ns.prices = ns.prices + [(1.25 * (float(state_attr('sensor.nordpool_kwh_dk1_dkk_3_10_0', 'today')[h]))) | round(5)] %}
              {% endfor %}
              {{ ns.prices }}
            {% endif %}
          tomorrow: >
            {% if state_attr('sensor.nordpool_kwh_dk1_dkk_3_10_0', 'tomorrow') %}
              {% set ns = namespace (prices=[]) %}
              {% for h in range(24) %}
                {% set ns.prices = ns.prices + [(1.25 * (float(state_attr('sensor.nordpool_kwh_dk1_dkk_3_10_0', 'tomorrow')[h]))) | round(5)] %}
              {% endfor %}
              {{ ns.prices }}
            {% endif %}
    sensor:
      - platform: systemmonitor
        resources:
          - type: memory_free
          - type: memory_use_percent
          - type: processor_use
          - type: processor_temperature
      - platform: steam_online
        api_key: !secret steamapikey
        accounts: 
          - 76561197983627921
      - platform: statistics
        entity_id: sensor.eloverblik_energy_total
        name: Eloverblik Monthly Statistics
        sampling_size: 50
        state_characteristic: mean
        max_age:
            days: 30

    binary_sensor:
      - platform: ping
        host: 192.168.87.183
        name: debian
        scan_interval: 30
      - platform: ping
        host: 192.168.87.113
        name: nakedpc
        scan_interval: 30
      - platform: ping
        host: 192.168.87.139
        name: closetpi
        scan_interval: 30
      - platform: ping
        host: 192.168.87.7
        name: closetpi_2
        scan_interval: 30
      - platform: ping
        host: 192.168.87.111
        name: raspberrypi
        scan_interval: 30

    group: !include groups.yaml
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    camera:
      - platform: xiaomi_cloud_map_extractor
        host: "192.168.87.180"
        token: !secret robot_token
        username: "Rasmus256@gmail.com"
        password: !secret robot_password
        name: "My Robot"
        colors:
          color_map_inside: [32, 115, 185]
          color_map_outside: [0,0,0,0]
          color_no_go_zones: [0, 33, 55, 127]
          color_no_go_zones_outline: [255, 0, 0]
        room_colors:
          1: [50,50,50]
          2: [50,50,50]
          3: [50,50,50]
          4: [50,50,50]
          5: [50,50,50]
          6: [50,50,50]
          7: [50,50,50]
          8: [50,50,50]
          9: [50,50,50]
          10: [50,50,50]
          11: [50,50,50]
          12: [50,50,50]
          13: [50,50,50]
          14: [50,50,50]
          15: [50,50,50]
          16: [50,50,50]
          17: [50,50,50]
          18: [50,50,50]
          19: [50,50,50]
          20: [50,50,50]
          21: [50,50,50]
          22: [50,50,50]
          23: [50,50,50]
          24: [50,50,50]
          25: [50,50,50]
          26: [50,50,50]
          27: [50,50,50]
          28: [50,50,50]
          29: [50,50,50]
          30: [50,50,50]
          31: [50,50,50]
          32: [50,50,50]
          33: [50,50,50]
          34: [50,50,50]
          35: [50,50,50]
          36: [50,50,50]
        draw: [
          "charger",
          "cleaned_area",
          "goto_path",
          "ignored_obstacles_with_photo",
          "ignored_obstacles",
          "no_go_zones",
          "obstacles_with_photo",
          "obstacles",
          "path",
          "predicted_path",
          "room_names",
          "vacuum_position",
          "virtual_walls"
          ]
        map_transformation:
          scale: 4
          rotate: 180
          trim:
            top: 20
            bottom: 20
            left: 30
            right: 20
        sizes:
          charger_radius: 10
          vacuum_radius: 8
        store_map_image: true
        store_map_path: "/config/www/custom-lovelace"
        auto_update: true
        attributes:
          - calibration_points
          - rooms
          - is_empty

    google_assistant:
      project_id: my-home-assistant-dfd19
      service_account: !include SERVICE_ACCOUNT.JSON
      report_state: true
      exposed_domains:
        - vacuum
        - light 
        - switch 
        - media_player
      entity_config:
        vacuum.ip:
          name: IP_STOVSUG
          aliases:
            - SPISEBORD
            - STØVSUG
        light.kids_light:
          name: toilet lights

    logger:
      default: info
  `}}
