apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: hass
  name: hass
spec:
  ports:
    - name: "8123"
      port: 8123
      targetPort: 8123
  selector:
    io.kompose.service: hass

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass-ingress
  annotations:
    acme.cert-manager.io/http01-ingress-class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: hass.hosrasmus.hopto.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hass
            port: 
              number: 8123
  tls:
  - secretName: hasscert-tls-cert
    hosts:
      - hass.hosrasmus.hopto.org
