apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\rasmu\cluster\kompose-windows-amd64.exe convert
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: hass
  name: hass
spec:
  ports:
    - name: "8123"
      port: 8123
      targetPort: 8123
  selector:
    io.kompose.service: hass
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hass
            port: 
              number: 8123
  tls:
  - secretName: hasscert-tls
    hosts:
      - hosrasmus.hopto.org

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hasscert
spec:
  # Secret names are always required.
  secretName: hasscert-tls
  duration: 1800h0m0s
  renewBefore: 360h0m0s # 15d
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - hosrasmus.hopto.org
    - "hosrasmus.hopto.org"
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
