apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume-hass
  namespace: hass
spec:
  volumeMode: Filesystem
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: pi
          operator: In
          values:
          - "true"

---

apiVersion: v1
kind: Namespace
metadata:
  name: hass

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: hass
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}