apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\rasmu\cluster\kompose-windows-amd64.exe convert
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: hass
  name: hass
spec:
  ports:
    - name: "8123"
      port: 8123
      targetPort: 8123
  selector:
    io.kompose.service: hass
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass-ingress
spec:
  rules:
  - host: DOMAIN
    http:
      paths:
      - backend:
          serviceName: hass
        pathType: Prefix
        path: /hass