apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\rasmu\cluster\kompose-windows-amd64.exe convert
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: valheim
  name: valheim
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      io.kompose.service: valheim
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: valheim
    spec:
      nodeSelector:
        name: "nakedpc"
      containers:
        - env:
            - name: SERVER_NAME
              value: "NewFaellesskab"
            - name: WORLD_NAME
              value: "142947"
            - name: SERVER_PASS
              valueFrom:
                secretKeyRef:
                  name: valheimpassword
                  key: password
                  optional: false
            - name: BACKUPS_MAX_AGE
              value: "10"
            - name: BACKUPS_IF_IDLE
              value: "false"
            - name: BACKUPS_IDLE_GRACE_PERIOD
              value: 1200
            - name: STATUS_HTTP
              value: "true"
            - name: STATUS_HTTP_PORT
              value: "30695"
            - name: SUPERVISOR_HTTP
              value: "true"
            - name: VALHEIM_PLUS
              value: "false"
          image: lloesche/valheim-server:latest
          name: valheim
          ports:
            - containerPort: 2456
            - containerPort: 2457
            - containerPort: 2458
            - containerPort: 30695
            - containerPort: 9001
          resources: 
            limits:
              cpu: 3000m 
              memory: 4Gi
            requests:
              cpu: 3000m
              memory: 4Gi
          volumeMounts:
            - mountPath: /config
              name: valheim-config2
            - mountPath: /opt/valheim
              name: valheim-storage2
      restartPolicy: Always
      volumes:
        - name: valheim-config2
          persistentVolumeClaim:
            claimName: valheim-config2
        - name: valheim-storage2
          persistentVolumeClaim:
            claimName: valheim-storage2
status: {}
