baseurl: chicken.hosrasmus.hopto.org
namespace: chicken
image:
  repository: rasmus256docker/chickenkeeper-backend
  tag: 2
uiImage:
  repository: rasmus256docker/chickenkeeper-frontend
  tag: 2
postgres:
  image:
    repository: postgres
    tag: 15-alpine
  user: chickenkeeper
  password: password
  database: chickenkeeper
  port: 5432
