---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: wordsolver
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
    version: {{ $.Chart.Version }}
  {{- $str := $.Values.title | lower}}
  {{- $str = print $str "-" $.Values.numNodes "-" $.Values.startNode | replace "," "-"  }}
  name: {{ $str }}
spec:
  completions: 1
  backoffLimit: 2
  template:
    spec:
    spec:
      containers:
      - image: "{{$.Values.image.repository }}:{{$.Values.image.tag | toString }}"
        imagePullPolicy: {{ $.Values.pullPolicy }}
        name: {{ $.Values.image.repository | toString | replace "/" "-" | replace "_" "-"}}-{{ $.Values.image.tag | toString | replace "." "-" }}
        env:          
          - name: "FIRST"
            value: "send"
          - name: "SECOND"
            value: "more"
          - name: "THIRD"
            value: "money"
      restartPolicy: Never
      
