apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.hosrasmus.hopto.org`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.hosrasmus.hopto.org`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: neverbeforeseensecretname
    
---


apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocert
  namespace: argocd
spec:
  # Secret names are always required.
  secretName: neverbeforeseensecretname
  duration: 24h0m0s
  renewBefore: 1h0m0s # 15d
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - argocd.hosrasmus.hopto.org
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
