apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argpcdingress
  namespace: argocd

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argocd.hosrasmus.hopto.org`)
      kind: Rule
      services:
        - name: argocd-server
          port: "http"
  tls:
    secretName: argocd2ingresssecretname
    options:
      name: opt
      namespace: argocd
    certResolver: letsencrypt-prod
    domains:
    - main: argocd.hosrasmus.hopto.org
