apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: argocd2.hosrasmus.hopto.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port: 
              name: "http"
  tls:
  - secretName: argocdingresssecretname
    hosts:
      - argocd2.hosrasmus.hopto.org
    
---


apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocert
  namespace: argocd
spec:
  # Secret names are always required.
  secretName: argocdingresssecretname
  duration: 2160h0m0s
  renewBefore: 360h0m0s # 15d
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - argocd2.hosrasmus.hopto.org
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
