baseurl: cake.hosrasmus.hopto.org
image:
  repository: rasmus256docker/cakeotron
  tag: 337
dateserviceImage:
  repository: rasmus256docker/cakeotron-dateservice
  tag: 337
uiImage:
  repository: rasmus256docker/cakeotron-ui
  tag: 337
