baseurl: cake.hosrasmus.hopto.org
image:
  repository: rasmus256docker/cakeotron
  tag: 343
dateserviceImage:
  repository: rasmus256docker/cakeotron-dateservice
  tag: 342
uiImage:
  repository: rasmus256docker/cakeotron-ui
  tag: 342
