kubernetes:
  host: https://kubernetes.default
namespace: default
pullPolicy: IfNotPresent
startNode: "185"
numNodes: 2003
blacklistedEdges: "0,0;1,1"
title: DDOExplorer
image:
  repository: rasmus256docker/ddoexplorer
  tag: 20230215-113358
