apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorer
  name: ddoexplorerui
spec:
  ports:
    - name: "ddoexplorerui"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexplorerui

---
apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorertwo
  name: ddoexploreruitwo
spec:
  ports:
    - name: "ddoexplorerui"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexploreruitwo

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ddoexplorerui
  namespace: ddoexplorer

spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.baseurl}}`)
      kind: Rule
      services:
        - name: ddoexplorerui
          port: 80
          weight: {{ .Values.canaryweight }}
        - name: ddoexploreruitwo
          port: 80
  tls:
    secretName: ddoexploreruicert-wild-4-tls
    options:
      name: opt
      namespace: ddoexplorer
    certResolver: letsencrypt-prod
    domains:
    - main: {{ .Values.baseurl}}
