apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddoexplorer
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorer
spec:
  replicas: 0
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      io.kompose.service: ddoexplorer
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: ddoexplorer
    spec:
      containers:
        - env:
            - name: "NUM_NODES"
              value: {{ $.Values.numNodes | quote }}
            - name: "BLACKLIST"
              value: {{ $.Values.blacklistedEdges |quote }}
            - name: "GREETING_MSG"
              value: "World"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 99999
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image: "{{$.Values.image.repository }}:{{$.Values.image.tag | toString }}"
          name: ddoexplorer
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "8Mi"
              cpu: "30m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 60
            initialDelaySeconds: 5
            timeoutSeconds: 1
      restartPolicy: Always
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddoexplorertwo
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorertwo
spec:
  replicas: 0
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      io.kompose.service: ddoexplorertwo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: ddoexplorertwo
    spec:
      containers:
        - env:
            - name: "NUM_NODES"
              value: {{ $.Values.numNodes | quote }}
            - name: "BLACKLIST"
              value: {{ $.Values.blacklistedEdges |quote }}
            - name: "GREETING_MSG"
              value: "Hello"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 99999
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image: "{{$.Values.canaryimage.repository }}:{{$.Values.canaryimage.tag | toString }}"
          name: ddoexplorertwo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "8Mi"
              cpu: "30m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 60
            initialDelaySeconds: 5
            timeoutSeconds: 1
      restartPolicy: Always
status: {}
