apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorer
  name: ddoexplorer
spec:
  ports:
    - name: "ddoexplorer"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexplorer

---
apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorertwo
  name: ddoexplorertwo
spec:
  ports:
    - name: "ddoexplorer"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexplorertwo
    
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: ddoexplorer

spec:
  entryPoints:
    - ddoexplorer
  routes:
    - match: Host(`ddoexplorer.hosramus.hopto.org`)
      kind: Rule
      services:
        - name: ddoexplorertwo
          port: 80
