apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorer
  name: ddoexplorer
spec:
  ports:
    - name: "ddoexplorer"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexplorer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ddoexplorer-ingress
  namespace: ddoexplorer
  annotations:
    acme.cert-manager.io/http01-ingress-class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: {{ .Values.baseurl}}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ddoexplorer
            port: 
              name: "ddoexplorer"
  tls:
  - secretName: ddoexplorercert-wild-4-tls
    hosts:
      - {{ .Values.baseurl}}
