apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorer
  name: ddoexplorer
spec:
  ports:
    - name: "ddoexplorer"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexplorer

---
apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorertwo
  name: ddoexplorertwo
spec:
  ports:
    - name: "ddoexplorer"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexplorertwo
---
apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorerui
  name: ddoexplorerui
spec:
  ports:
    - name: "ddoexplorerui"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexplorerui

---
apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexploreruitwo
  name: ddoexploreruitwo
spec:
  ports:
    - name: "ddoexplorerui"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexploreruitwo

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ddoexplorer
  namespace: ddoexplorer

spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.baseurl}}`) &&  PathPrefix(`/api`)
      kind: Rule
      services:
        - name: ddoexplorer
          port: 80
          weight: {{ .Values.canaryweight }}
        - name: ddoexplorertwo
          port: 80
    - match: Host(`{{ .Values.baseurl}}`)
      kind: Rule
      services:
        - name: ddoexplorerui
          port: 80
          weight: {{ .Values.canaryweight }}
        - name: ddoexploreruitwo
          port: 80
  tls:
    secretName: ddoexplorercert-wild-5-tls
    options:
      name: opt
      namespace: ddoexplorer
    certResolver: letsencrypt-prod
    domains:
    - main: {{ .Values.baseurl}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ddoexplorer-cert
  namespace: ddoexplorer
spec:
  # Secret names are always required.
  secretName: ddoexplorercert-wild-5-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s # 15d
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - {{ .Values.baseurl}}
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
