apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorer
  name: ddoexplorer
spec:
  ports:
    - name: "ddoexplorer"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexplorer

---
apiVersion: v1
kind: Service
metadata:
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorertwo
  name: ddoexplorertwo
spec:
  ports:
    - name: "ddoexplorer"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ddoexplorertwo

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ddoexplorer
  namespace: ddoexplorer

spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.baseurl}}`)
      kind: Rule
      services:
        - name: ddoexplorer
          port: 80
          weight: 2
        - name: ddoexplorertwo
          port: 80
  tls:
    secretName: ddoexplorercert-wild-4-tls
    options:
      name: opt
      namespace: ddoexplorer
    certResolver: letsencrypt-prod
    domains:
    - main: {{ .Values.baseurl}}
