apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddoexplorer
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorer
spec:
  revisionHistoryLimit: 1
  replicas: 1
  minReadySeconds: 1
  selector:
    matchLabels:
      io.kompose.service: ddoexplorer
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: ddoexplorer
    spec:
      containers:
        - env:
            - name: "NUM_NODES"
              value: {{ $.Values.numNodes | quote }}
            - name: "BLACKLIST"
              value: {{ $.Values.blacklistedEdges |quote }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 99999
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image: "{{$.Values.image.repository }}:{{$.Values.image.tag | toString }}"
          name: ddoexplorer
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "8Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
status: {}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ddoexplorerscaler
  namespace: ddoexplorer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ddoexplorer
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
