apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddoexplorerui
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexplorerui
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      io.kompose.service: ddoexplorerui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: ddoexplorerui
    spec:
      containers:
        - image: "{{$.Values.image.repository }}:{{$.Values.image.tag | toString }}"
          name: ddoexplorerui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "8Mi"
              cpu: "30m"
            limits:
              memory: "64Mi"
              cpu: "50m"
      restartPolicy: Always
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddoexploreruitwo
  namespace: ddoexplorer
  labels:
    io.kompose.service: ddoexploreruitwo
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      io.kompose.service: ddoexploreruitwo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: ddoexploreruitwo
    spec:
      containers:
        - image: "{{$.Values.image.repository }}:{{$.Values.image.tag | toString }}"
          name: ddoexploreruitwo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "8Mi"
              cpu: "30m"
            limits:
              memory: "64Mi"
              cpu: "50m"
      restartPolicy: Always
status: {}