apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotifyrandom
  namespace: argocd
  labels:
    "category": "{{$.Values.spec.labels.category}}"
spec:
  destination:
    namespace: spotifyrandom
    server: 'https://kubernetes.default.svc'
  source:
    path: low-prio-apps/spotify-random-album
    repoURL: 'git@github.com:Rasmus256/homeArgocdProject.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
