apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mc2
  namespace: argocd
  labels:
    "category": "{{$.Values.spec.labels.category}}"
spec:
  destination:
    namespace: minecraft
    server: 'https://kubernetes.default.svc'
  source:
    path: gameservers/mc2
    repoURL: 'git@github.com:Rasmus256/homeArgocdProject.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
