apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mcbedrock
  name: mcbedrock
spec:
  ports:
    - name: "19132"
      port: 19132
      targetPort: 19132
      protocol: UDP

  type: LoadBalancer
  selector:
    io.kompose.service: mcbedrock
    
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mc2-ingress
spec:
  rules:
  - host: mc.hosrasmus.hopto.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mcbedrock
            port: 
              number: 8123
