apiVersion: apps/v1
kind: Deployment
metadata:
  name: cakeotron
  namespace: cake
  labels:
    io.kompose.service: cakeotron
spec:
  replicas: 80
  minReadySeconds: 2
  selector:
    matchLabels:
      io.kompose.service: cakeotron
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: cakeotron
    spec:
      containers:
        - env:
          - name: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
            value: "false"
          image: rasmus256docker/cakeotron:latest
          name: cakeotron
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "8Mi"
              cpu: "0.01m"
            limits:
              memory: "64Mi"
              cpu: "50m"
      restartPolicy: Always
status: {}
