---
apiVersion: v1
kind: List
items:
{{- range $startNode := split "," $.Values.startNode }}
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      app: helloworld
      chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
      release: {{ $.Release.Name | quote }}
      heritage: {{ $.Release.Service | quote }}
      version: {{ $.Chart.Version }}
    {{- $str := $.Values.title | lower}}
    {{- $postfix := print $startNode "-" $.Values.numNodes "-" $.Values.blacklistedEdges | adler32sum  }}
    {{- $str = print $str "-" $startNode "-" $postfix | replace "," "-" | lower }}
    {{- range $i, $e := $.Values.parts }}
    {{- $str = print $str "-" $e.image.tag }}
    {{- end }}
    name: {{ $str }}
  spec:
    completions: 1
    backoffLimit: 2
    template:
      spec:
      spec:
        containers:
        - image: "{{$e.image.repository }}:{{$e.image.tag | toString }}"
          imagePullPolicy: {{ $.Values.pullPolicy }}
          name: {{ $e.image.repository | toString | replace "/" "-" | replace "_" "-"}}-{{ $e.image.tag | toString | replace "." "-" }}
          env:          
            - name: "NUM_NODES"
              value: {{$.Values.numNodes | quote}}
            - name: "START_NODE"
              value: {{$startNode |quote}}
            - name: "BLACKLIST"
              value: {{$.Values.blacklistedEdges |quote}}
        restartPolicy: Never
        nodeSelector:
          kubernetes.io/arch: amd64
        
{{- end }}
