apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: amq
  namespace: adventofcode
  labels:
    io.kompose.service: amq
spec:
  deploymentPlan:
    size: 1
    image: placeholder
  acceptors:
  - name: "stomp"
    port: 61613
    protocols: stomp
